[build]
command = "npm run build"
publish = "build/"  

[[headers]]
  for = "/*"
  
   [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "fullscreen=(self 'https://emmasarge-developer.com'), geolocation=*, camera=*"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200


