[[headers]]
  for = "/*"
  
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

    Permissions-Policy = "ch-ua-form-factor none"




[[redirects]]
  from = "/*"
  to = "/"
  status = 200


